/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RfAudioEq {
        "audioSource": string;
        "color": string;
    }
    interface WsAudioPlayer {
        /**
          * The Link To The Audio File
         */
        "audio": string;
        /**
          * The waveform color
         */
        "color": string;
        "create": () => Promise<void>;
        "duration": string;
        /**
          * optional external Visualizer Web Component /: Component tag name
         */
        "externalVisualizer": string;
        /**
          * optional external Visualizer Container :  element selector
         */
        "externalVisualizerContainer": string;
        /**
          * The height of the waveform
         */
        "height": string;
        "playpause": () => Promise<void>;
        /**
          * The waveform color
         */
        "progressColor": string;
        /**
          * The player theme
         */
        "theme": string;
        /**
          * The Track Title
         */
        "trackTitle": string;
    }
}
declare global {
    interface HTMLRfAudioEqElement extends Components.RfAudioEq, HTMLStencilElement {
    }
    var HTMLRfAudioEqElement: {
        prototype: HTMLRfAudioEqElement;
        new (): HTMLRfAudioEqElement;
    };
    interface HTMLWsAudioPlayerElement extends Components.WsAudioPlayer, HTMLStencilElement {
    }
    var HTMLWsAudioPlayerElement: {
        prototype: HTMLWsAudioPlayerElement;
        new (): HTMLWsAudioPlayerElement;
    };
    interface HTMLElementTagNameMap {
        "rf-audio-eq": HTMLRfAudioEqElement;
        "ws-audio-player": HTMLWsAudioPlayerElement;
    }
}
declare namespace LocalJSX {
    interface RfAudioEq {
        "audioSource"?: string;
        "color"?: string;
    }
    interface WsAudioPlayer {
        /**
          * The Link To The Audio File
         */
        "audio"?: string;
        /**
          * The waveform color
         */
        "color"?: string;
        "duration"?: string;
        /**
          * optional external Visualizer Web Component /: Component tag name
         */
        "externalVisualizer"?: string;
        /**
          * optional external Visualizer Container :  element selector
         */
        "externalVisualizerContainer"?: string;
        /**
          * The height of the waveform
         */
        "height"?: string;
        /**
          * The waveform color
         */
        "progressColor"?: string;
        /**
          * The player theme
         */
        "theme"?: string;
        /**
          * The Track Title
         */
        "trackTitle"?: string;
    }
    interface IntrinsicElements {
        "rf-audio-eq": RfAudioEq;
        "ws-audio-player": WsAudioPlayer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rf-audio-eq": LocalJSX.RfAudioEq & JSXBase.HTMLAttributes<HTMLRfAudioEqElement>;
            "ws-audio-player": LocalJSX.WsAudioPlayer & JSXBase.HTMLAttributes<HTMLWsAudioPlayerElement>;
        }
    }
}
